version: '3.8'
name: mmogamemai
services:
  client:
    build: ./client
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://mmogamemai.onrender.com

  server:
    build: ./server
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mmodb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mmodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
